### ISSUE TITLE
Utiliza definition environment

### ISSUE THREAD

**Issue by BraulioVM** [santidediego/Probabilidad-I-DGIIM#1]
Estaría bien actualizar el capítulo que he escrito sobre límites de sucesiones de conjuntos para que hiciera uso de los *environments* para definiciones. Básicamente sería hacer algo así:

````tex
\begin{definition}
Sea $\{A_n\}_{n\in\mathbb{N}}$ una sucesión creciente de conjuntos, entonces diremos que esta sucesión tiene límite y que 
$$ \lim_{n\to\infty} = \bigcup_{n\in\mathbb{N}} A_n $$
\end{definition}
````

Habría que escribir así por ahora las definiciones de límite para sucesiones crecientes, decrecientes, la de límite inferior, superior y la de límite para sucesiones arbitrarias de conjuntos.

**Comment by santidediego** [comment]
Ok
